# Generated by Django 4.2.4 on 2023-09-25 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
